//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGBK3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitiethoadonHP
    {
        public string ChitiethoadonHP_ID { get; set; }
        public string HoadonHP_ID { get; set; }
        public string LopCLB_ID { get; set; }
        public int Hocphi { get; set; }
    
        public virtual Hoadonhocphi Hoadonhocphi { get; set; }
        public virtual LopCLB LopCLB { get; set; }
    }
}
