//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGBK3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLB
    {
        public CLB()
        {
            this.LopCLBs = new HashSet<LopCLB>();
        }
    
        public string CLB_ID { get; set; }
        public string TenCLB { get; set; }
    
        public virtual ICollection<LopCLB> LopCLBs { get; set; }
    }
}
