//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGBK3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MGBKEntities : DbContext
    {
        public MGBKEntities()
            : base("name=MGBKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChitiethoadonHP> ChitiethoadonHPs { get; set; }
        public DbSet<CLB> CLBs { get; set; }
        public DbSet<Hoadonhocphi> Hoadonhocphis { get; set; }
        public DbSet<Hocsinh> Hocsinhs { get; set; }
        public DbSet<LopCLB> LopCLBs { get; set; }
        public DbSet<LopHanhchinh> LopHanhchinhs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
