//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGBK3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadonhocphi
    {
        public Hoadonhocphi()
        {
            this.ChitiethoadonHPs = new HashSet<ChitiethoadonHP>();
        }
    
        public int HoadonHP_ID { get; set; }
        public Nullable<int> Sotien { get; set; }
        public Nullable<bool> Trangthai { get; set; }
        public Nullable<System.DateTime> Thoigiandong { get; set; }
        public string Nguoidong { get; set; }
        public Nullable<int> Hocsinh_ID { get; set; }
    
        public virtual ICollection<ChitiethoadonHP> ChitiethoadonHPs { get; set; }
        public virtual Hocsinh Hocsinh { get; set; }
    }
}
