//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGBK3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hocsinh
    {
        public Hocsinh()
        {
            this.Hoadonhocphis = new HashSet<Hoadonhocphi>();
        }
    
        public string Hocsinh_ID { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public Nullable<bool> Gioitinh { get; set; }
        public string Diachi { get; set; }
        public string LopHC_ID { get; set; }
    
        public virtual ICollection<Hoadonhocphi> Hoadonhocphis { get; set; }
        public virtual LopHanhchinh LopHanhchinh { get; set; }
    }
}
