//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGBK3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopCLB
    {
        public LopCLB()
        {
            this.ChitiethoadonHPs = new HashSet<ChitiethoadonHP>();
        }
    
        public string LopCLB_ID { get; set; }
        public string TenLopCLB { get; set; }
        public Nullable<int> Hocphi { get; set; }
        public string CLB_ID { get; set; }
        public string Lichhoc { get; set; }
    
        public virtual ICollection<ChitiethoadonHP> ChitiethoadonHPs { get; set; }
        public virtual CLB CLB { get; set; }
    }
}
