//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGBK3
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHanhchinh
    {
        public LopHanhchinh()
        {
            this.Hocsinhs = new HashSet<Hocsinh>();
        }
    
        public int LopHC_ID { get; set; }
        public string TenLopHC { get; set; }
        public string Khoahoc { get; set; }
        public Nullable<int> Namhoc { get; set; }
    
        public virtual ICollection<Hocsinh> Hocsinhs { get; set; }
    }
}
